MODEL:
  META_ARCHITECTURE: "FCOS"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  FCOS:
    NUM_CLASSES: 80
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    NUM_CONVS: 4
    FPN_STRIDES: [8, 16, 32, 64, 128]
    PRIOR_PROB: 0.01
    CENTERNESS_ON_REG: False
    NORM_REG_TARGETS: False
    SCORE_THRESH_TEST: 0.05
    TOPK_CANDIDATES_TEST: 1000
    NMS_THRESH_TEST: 0.6
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
    FOCAL_LOSS_GAMMA: 2.0
    FOCAL_LOSS_ALPHA: 0.25
    IOU_LOSS_TYPE: "iou"
    CENTER_SAMPLING_RADIUS: 0.0
    OBJECT_SIZES_OF_INTEREST: [[-1, 64],[64, 128],[128, 256],[256, 512],[512, .inf],]
    NORM_SYNC: False
DATASETS:
  TRAIN: ("coco_2014_train",)
  TEST: ("coco_2014_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
