_BASE_: "Base-FCOS-FPN.yaml"
MODEL:
  WEIGHTS: "pretrained_weights/FCOS_imprv_R_50_FPN_1x.pth"
  RESNETS:
    NORM: "FrozenBN" # default
    DEPTH: 50 # default
  BACKBONE:
    FREEZE_AT: 3 # custom, freeze the first 3 Resnet stages so they are not trained
  FCOS:
    NUM_CLASSES: 80
    CENTERNESS_ON_REG: True
    NORM_REG_TARGETS: True
    NMS_THRESH_TEST: 0.6
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
    FOCAL_LOSS_GAMMA: 2.0
    FOCAL_LOSS_ALPHA: 0.25
    IOU_LOSS_TYPE: "giou"
    CENTER_SAMPLING_RADIUS: 1.5
    OBJECT_SIZES_OF_INTEREST: [[-1, 64],[64, 128],[128, 256],[256, 512],[512, .inf],]
    NORM_SYNC: False
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 2
  BASE_LR: 0.01
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800) # default
  MAX_SIZE_TRAIN: 1333 # default
#  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640)
#  MAX_SIZE_TRAIN: 640
#  MIN_SIZE_TEST: 480
#  MAX_SIZE_TEST: 480

OUTPUT_DIR: "./output/fcos_R_50_FPN"
